---
- name: "install UFW"
  apt:
    name: ufw
    update_cache: yes
    state: latest

- name: "setup firewall"
  shell: |
    ufw allow ssh
    ufw allow http
    ufw allow https
    ufw --force enable
