---
- name: "create wiki container"
  docker_container:
    name: wiki
    hostname: wiki
    image: "ghcr.io/requarks/wiki:2"
    state: started
    ports:
      - "80:3000"
      - "443:3443"
    env:
      DB_TYPE: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_PASS_FILE: "/etc/wiki/.db-secret"
      DB_USER: "wiki"
      DB_NAME: "wiki"
      UPGRADE_COMPANION: "1"
      LETSENCRYPT_DOMAIN: "wiki.example.com"
      LETSENCRYPT_EMAIL: "admin@example.com"
      SSL_ACTIVE: "1"
    restart_policy: unless-stopped
    volumes:
      - "/etc/wiki/.db-secret:/etc/wiki/.db-secret:ro"
    networks:
      - name: wikinet
