---
- name: "install dependencies to install docker"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - openssl
    state: latest
    update_cache: true
    dpkg_options: "force-confdef,force-confold"

- name: "add key for docker package registry"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "register docker package registry"
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: "refresh package udpates and install docker"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true
    dpkg_options: "force-confdef,force-confold"
